
services:

  nats-server:
    image: nats
    container_name: nats-server
    ports:
      - "8222:8222"
      # - "4222:4222"
      # - "6222:6222"


  # ############################################
  # ## CLIENT GATEWAY
  # ############################################
  client-gateway:
    build: 
      context: ./client-geteway
      dockerfile: dockerfile.prod
    container_name: client-gateway-prod
    image: southamerica-west1-docker.pkg.dev/tienda-microservicios-454313/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222    

  # # ############################################
  # # ## PRODUCTS MICROSERVICE
  # # ############################################
  products-ms:
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    container_name: products-ms
    image: southamerica-west1-docker.pkg.dev/tienda-microservicios-454313/image-registry/products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  # # ############################################
  # # ## ORDERS MICROSERVICE
  # # ############################################
  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    container_name: orders-ms
    image: southamerica-west1-docker.pkg.dev/tienda-microservicios-454313/image-registry/orders-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  # # ############################################
  # # ## PAYMENTS MICROSERVICE
  # # ############################################
  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    container_name: payments-ms
    image: southamerica-west1-docker.pkg.dev/tienda-microservicios-454313/image-registry/payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}    
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

  # # ############################################
  # # ## AUTH MICROSERVICE
  # # ############################################
  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    container_name: auth-ms
    image: southamerica-west1-docker.pkg.dev/tienda-microservicios-454313/image-registry/auth-ms
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
